# Generated by Django 5.1.7 on 2025-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='hi', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='prfile_picture',
            field=models.ImageField(null=True, upload_to='user_image'),
        ),
    ]
