# Generated by Django 5.1.7 on 2025-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_picture',
            field=models.ImageField(default=2, upload_to='blogs/'),
            preserve_default=False,
        ),
    ]
